In [1]:
MAZE_DATA = ["""
    -10;-1;-10;-10;
    -10;-1;-1;-10;
    -1;-10;-1;-10;
    -10;-1;-10;-10;
    -10;-1;-1;-10;
    -10;-1;-1;-10;
    -1;-1;-1;-10;
    -10;-1;-1;-10;
    -10;-1;-1;-10;
    -1;-10;-1;-10;
    -1;-10;-10;-10;
    -1;-1;-10;-10;
    -10;-10;-1;-1;
    -1;-1;-10;-10;
    -10;-1;-1;-10;
    -1;-10;-1;-10;
    -1;-10;-10;-1;
    -10;-1;-10;-10;
    -10;-1;-1;-10;
    -1;-10;-1;-1;
    -1;-1;-10;-1;
    -10;-10;-1;-1;
    -1;-1;-10;-10;
    -10;-1;-1;-1;
    -1;-10;-1;-10;
    -10;-1;-10;-1;
    -1;-10;-1;-1;
    -1;-1;-10;-10;
    -1;-10;-1;-10;
    -1;-10;-10;-1;
    -1;-10;-10;-1;
    -1;-10;-10;-10;
    -1;-10;-10;-1;
    -1;-10;-10;-10;
    -1;-10;-10;-1;
    -10;-1;-10;-10;
    -1;-10;-1;-1;
    -1;-10;-10;-1;
    -1;-10;-10;-1;
    -10;-10;-10;-1;
    -1;-10;-10;-1;
    -1;-10;-10;-1;
    -10;-1;-10;-1;
    -1;-10;-1;-1;
    -10;-1;-10;-1;
    -1;-10;-1;-10;
    -10;-10;-10;-1;
    -1;-10;-10;-1;
    -10;-1;-10;-1;
    -1;-10;-1;-10;
    -1;-10;-10;-1;
    -1;-1;-10;-1;
    -10;-10;-1;-10;
    -10;-1;-10;-1;
    -1;-10;-1;-10;
    -10;-1;-10;-1;
    -10;-1;-1;-10;
    -10;-1;-1;-1;
    -10;-10;-1;-10;
    -1;-10;-10;-1;
    -1;-10;-10;-1;
    -10;-1;-10;-1;
    -10;-1;-1;-10;
    -10;-1;-1;-10;
    -1;-1;-1;-1;
    -10;-1;-1;-10;
    -10;-1;-1;-10;
    -10;-10;-1;-10;
    -1;-1;-10;-10;
    -1;-10;-1;-1;
    -1;-10;-10;-1;
    -1;-1;-10;-10;
    -10;-1;-1;-10;
    -1;-10;-1;-10;
    -10;-10;-10;-1;
    -1;-1;-10;-10;
    -10;-1;-1;-10;
    -1;-10;-1;-10;
    -1;-10;-10;-1;
    -1;-10;-10;-1;
    -1;-10;-10;-1;
    -1;-10;-10;-1;
    -1;-1;-10;-10;
    -10;-10;-1;-1;
    -1;-1;-10;-10;
    -10;-10;-1;-1;
    -1;-10;-10;-10;
    -1;-10;-10;-1;
    -1;-10;-10;-1;
    -1;-10;-10;-1;
    -10;-1;-10;-1;
    -10;-10;-1;-1;
    -10;-1;-10;-1;
    -10;-1;-1;-10;
    -10;-10;-1;-1;
    -10;-1;-10;-10;
    -10;-1;-1;-1;
    -10;-1;-1;-1;
    -10;-10;-1;-1;
    -10;-10;-10;-1;
        """]

In [2]:
maze_data_list = [
    """
    -10;-1;-10;-10;
    -10;-1;-1;-10;
    -1;-10;-1;-10;
    -10;-1;-10;-10;
    -10;-1;-1;-10;
    -10;-1;-1;-10;
    -1;-1;-1;-10;
    -10;-1;-1;-10;
    -10;-1;-1;-10;
    -1;-10;-1;-10;
    -1;-10;-10;-10;
    -1;-1;-10;-10;
    -10;-10;-1;-1;
    -1;-1;-10;-10;
    -10;-1;-1;-10;
    -1;-10;-1;-10;
    -1;-10;-10;-1;
    -10;-1;-10;-10;
    -10;-1;-1;-10;
    -1;-10;-1;-1;
    -1;-1;-10;-1;
    -10;-10;-1;-1;
    -1;-1;-10;-10;
    -10;-1;-1;-1;
    -1;-10;-1;-10;
    -10;-1;-10;-1;
    -1;-10;-1;-1;
    -1;-1;-10;-10;
    -1;-10;-1;-10;
    -1;-10;-10;-1;
    -1;-10;-10;-1;
    -1;-10;-10;-10;
    -1;-10;-10;-1;
    -1;-10;-10;-10;
    -1;-10;-10;-1;
    -10;-1;-10;-10;
    -1;-10;-1;-1;
    -1;-10;-10;-1;
    -1;-10;-10;-1;
    -10;-10;-10;-1;
    -1;-10;-10;-1;
    -1;-10;-10;-1;
    -10;-1;-10;-1;
    -1;-10;-1;-1;
    -10;-1;-10;-1;
    -1;-10;-1;-10;
    -10;-10;-10;-1;
    -1;-10;-10;-1;
    -10;-1;-10;-1;
    -1;-10;-1;-10;
    -1;-10;-10;-1;
    -1;-1;-10;-1;
    -10;-10;-1;-10;
    -10;-1;-10;-1;
    -1;-10;-1;-10;
    -10;-1;-10;-1;
    -10;-1;-1;-10;
    -10;-1;-1;-1;
    -10;-10;-1;-10;
    -1;-10;-10;-1;
    -1;-10;-10;-1;
    -10;-1;-10;-1;
    -10;-1;-1;-10;
    -10;-1;-1;-10;
    -1;-1;-1;-1;
    -10;-1;-1;-10;
    -10;-1;-1;-10;
    -10;-10;-1;-10;
    -1;-1;-10;-10;
    -1;-10;-1;-1;
    -1;-10;-10;-1;
    -1;-1;-10;-10;
    -10;-1;-1;-10;
    -1;-10;-1;-10;
    -10;-10;-10;-1;
    -1;-1;-10;-10;
    -10;-1;-1;-10;
    -1;-10;-1;-10;
    -1;-10;-10;-1;
    -1;-10;-10;-1;
    -1;-10;-10;-1;
    -1;-10;-10;-1;
    -1;-1;-10;-10;
    -10;-10;-1;-1;
    -1;-1;-10;-10;
    -10;-10;-1;-1;
    -1;-10;-10;-10;
    -1;-10;-10;-1;
    -1;-10;-10;-1;
    -1;-10;-10;-1;
    -10;-1;-10;-1;
    -10;-10;-1;-1;
    -10;-1;-10;-1;
    -10;-1;-1;-10;
    -10;-10;-1;-1;
    -10;-1;-10;-10;
    -10;-1;-1;-1;
    -10;-1;-1;-1;
    -10;-10;-1;-1;
    -10;-10;-10;-1;
    """,
    """
    -1;-10;-10;-10;
    -1;-1;-10;-10;
    -1;-1;-1;-10;
    -10;-10;-1;-10;
    -1;-1;-10;-10;
    -1;-10;-1;-10;
    -10;-1;-10;-10;
    -1;-1;-1;-10;
    -1;-10;-1;-10;
    -1;-10;-10;-10;
    -10;-1;-10;-1;
    -10;-10;-1;-1;
    -1;-10;-10;-1;
    -10;-1;-10;-10;
    -10;-10;-1;-1;
    -10;-1;-10;-1;
    -1;-10;-1;-10;
    -1;-10;-10;-1;
    -10;-1;-10;-1;
    -10;-10;-1;-1;
    -1;-1;-10;-10;
    -10;-1;-1;-10;
    -10;-1;-1;-1;
    -1;-10;-1;-10;
    -1;-1;-10;-10;
    -10;-1;-1;-10;
    -10;-10;-1;-1;
    -1;-10;-10;-1;
    -1;-1;-10;-10;
    -1;-10;-1;-10;
    -1;-1;-10;-1;
    -1;-10;-1;-10;
    -10;-1;-10;-10;
    -1;-10;-1;-1;
    -10;-1;-10;-1;
    -10;-1;-1;-10;
    -1;-10;-1;-10;
    -10;-1;-10;-1;
    -10;-10;-1;-1;
    -1;-10;-10;-1;
    -1;-10;-10;-1;
    -10;-1;-10;-1;
    -1;-10;-1;-10;
    -1;-10;-10;-1;
    -1;-1;-10;-10;
    -1;-10;-1;-10;
    -1;-10;-10;-1;
    -1;-1;-10;-10;
    -1;-10;-1;-10;
    -1;-10;-10;-1;
    -1;-10;-10;-1;
    -1;-10;-10;-10;
    -1;-10;-10;-1;
    -10;-1;-10;-1;
    -10;-10;-1;-1;
    -1;-10;-10;-1;
    -10;-1;-10;-1;
    -10;-10;-1;-1;
    -1;-10;-10;-1;
    -1;-10;-10;-1;
    -1;-1;-10;-1;
    -10;-10;-1;-1;
    -1;-10;-10;-1;
    -1;-1;-10;-10;
    -10;-1;-1;-10;
    -10;-1;-1;-1;
    -10;-1;-1;-10;
    -10;-10;-1;-10;
    -10;-1;-10;-1;
    -1;-10;-1;-1;
    -10;-10;-10;-1;
    -1;-1;-10;-10;
    -10;-10;-1;-1;
    -10;-10;-10;-1;
    -1;-1;-10;-10;
    -10;-1;-1;-10;
    -10;-1;-1;-10;
    -10;-1;-1;-10;
    -1;-10;-1;-10;
    -1;-10;-10;-1;
    -1;-1;-10;-10;
    -10;-10;-1;-1;
    -1;-1;-10;-10;
    -1;-10;-1;-10;
    -10;-1;-10;-1;
    -10;-1;-1;-10;
    -1;-10;-1;-10;
    -1;-10;-10;-10;
    -10;-1;-10;-1;
    -10;-10;-1;-1;
    -10;-1;-10;-1;
    -10;-1;-1;-10;
    -10;-10;-1;-1;
    -10;-1;-10;-1;
    -10;-1;-1;-10;
    -10;-1;-1;-10;
    -10;-1;-1;-1;
    -10;-1;-1;-1;
    -10;-1;-1;-10;
    -10;-10;-1;-10;
    """,
    """
    -1;-1;-10;-10;
    -10;-10;-1;-10;
    -1;-1;-10;-10;
    -1;-10;-1;-10;
    -1;-1;-10;-10;
    -10;-1;-1;-10;
    -1;-1;-1;-10;
    -10;-1;-1;-10;
    -1;-10;-1;-10;
    -1;-10;-10;-10;
    -1;-10;-10;-1;
    -1;-1;-10;-10;
    -10;-10;-1;-1;
    -10;-1;-10;-1;
    -10;-1;-1;-1;
    -10;-10;-1;-10;
    -1;-10;-10;-1;
    -1;-10;-10;-10;
    -10;-1;-10;-1;
    -1;-10;-1;-1;
    -1;-10;-10;-1;
    -10;-1;-10;-1;
    -1;-10;-1;-10;
    -1;-10;-10;-10;
    -1;-1;-10;-10;
    -10;-1;-1;-10;
    -10;-10;-1;-1;
    -1;-1;-10;-1;
    -10;-10;-1;-10;
    -1;-10;-10;-1;
    -10;-1;-10;-1;
    -10;-1;-1;-10;
    -10;-1;-1;-1;
    -1;-10;-1;-1;
    -10;-1;-10;-1;
    -10;-1;-1;-10;
    -1;-10;-1;-10;
    -1;-10;-10;-1;
    -1;-1;-10;-10;
    -10;-10;-1;-1;
    -1;-1;-10;-10;
    -10;-1;-1;-10;
    -1;-10;-1;-10;
    -1;-10;-10;-1;
    -1;-1;-10;-10;
    -10;-1;-1;-10;
    -10;-10;-1;-1;
    -10;-1;-10;-1;
    -10;-1;-1;-1;
    -1;-10;-1;-10;
    -1;-10;-10;-1;
    -1;-1;-10;-10;
    -10;-10;-1;-1;
    -10;-10;-10;-1;
    -10;-1;-10;-1;
    -10;-1;-1;-10;
    -1;-10;-1;-10;
    -1;-1;-10;-10;
    -1;-10;-1;-10;
    -1;-10;-10;-1;
    -1;-10;-10;-1;
    -1;-10;-10;-1;
    -1;-1;-10;-10;
    -1;-10;-1;-10;
    -1;-1;-10;-10;
    -1;-10;-1;-10;
    -10;-1;-10;-1;
    -10;-10;-1;-1;
    -1;-10;-10;-1;
    -1;-10;-10;-1;
    -1;-10;-10;-1;
    -10;-1;-10;-1;
    -10;-10;-1;-1;
    -10;-1;-10;-1;
    -10;-10;-1;-1;
    -10;-1;-10;-1;
    -10;-1;-1;-10;
    -10;-1;-1;-10;
    -10;-10;-1;-1;
    -1;-10;-10;-1;
    -1;-1;-10;-1;
    -1;-10;-1;-10;
    -10;-1;-10;-10;
    -1;-1;-1;-10;
    -10;-10;-1;-10;
    -1;-1;-10;-10;
    -1;-10;-1;-10;
    -1;-1;-10;-10;
    -10;-1;-1;-10;
    -10;-10;-1;-1;
    -10;-10;-10;-1;
    -10;-1;-10;-1;
    -10;-10;-1;-10;
    -10;-1;-10;-1;
    -10;-1;-1;-10;
    -10;-10;-1;-1;
    -10;-1;-10;-1;
    -10;-1;-1;-1;
    -10;-1;-1;-10;
    -10;-10;-1;-10;
    """,
    """
    -1;-1;-10;-10;
    -10;-10;-1;-10;
    -1;-1;-10;-10;
    -10;-1;-1;-10;
    -10;-1;-1;-10;
    -10;-1;-1;-10;
    -10;-1;-1;-10;
    -1;-1;-1;-10;
    -1;-10;-1;-10;
    -1;-10;-10;-10;
    -1;-1;-10;-1;
    -1;-10;-1;-10;
    -1;-10;-10;-1;
    -10;-1;-10;-10;
    -1;-10;-1;-10;
    -1;-1;-10;-10;
    -10;-1;-1;-10;
    -10;-10;-1;-1;
    -10;-1;-10;-1;
    -1;-10;-1;-1;
    -1;-10;-10;-1;
    -1;-10;-10;-1;
    -10;-1;-10;-1;
    -10;-1;-1;-10;
    -1;-10;-1;-1;
    -10;-1;-10;-1;
    -10;-1;-1;-10;
    -1;-10;-1;-10;
    -1;-10;-10;-10;
    -1;-10;-10;-1;
    -1;-10;-10;-1;
    -1;-10;-10;-1;
    -1;-1;-10;-10;
    -1;-10;-1;-10;
    -1;-10;-10;-1;
    -1;-1;-10;-10;
    -10;-1;-1;-10;
    -10;-10;-1;-1;
    -1;-1;-10;-1;
    -10;-10;-1;-1;
    -1;-10;-10;-1;
    -10;-1;-10;-1;
    -10;-10;-1;-1;
    -10;-1;-10;-1;
    -10;-10;-1;-1;
    -10;-1;-10;-1;
    -10;-1;-1;-10;
    -1;-10;-1;-10;
    -10;-1;-10;-1;
    -1;-10;-1;-10;
    -1;-10;-10;-1;
    -10;-1;-10;-10;
    -1;-1;-1;-10;
    -10;-1;-1;-10;
    -1;-1;-1;-10;
    -10;-1;-1;-10;
    -10;-10;-1;-10;
    -10;-1;-10;-1;
    -1;-10;-1;-10;
    -1;-10;-10;-1;
    -10;-1;-10;-1;
    -10;-1;-1;-10;
    -10;-10;-1;-1;
    -1;-1;-10;-10;
    -10;-10;-1;-1;
    -1;-1;-10;-10;
    -10;-10;-1;-10;
    -1;-1;-10;-10;
    -10;-10;-1;-1;
    -1;-10;-10;-1;
    -1;-1;-10;-10;
    -1;-1;-1;-10;
    -1;-10;-1;-10;
    -1;-10;-10;-1;
    -1;-10;-10;-10;
    -1;-10;-10;-1;
    -10;-1;-10;-10;
    -1;-10;-1;-1;
    -1;-10;-10;-10;
    -1;-10;-10;-1;
    -1;-10;-10;-1;
    -1;-10;-10;-1;
    -10;-10;-10;-1;
    -1;-10;-10;-1;
    -1;-10;-10;-1;
    -10;-1;-10;-1;
    -1;-10;-1;-10;
    -1;-10;-10;-1;
    -1;-1;-10;-1;
    -10;-10;-1;-1;
    -10;-10;-10;-1;
    -10;-1;-10;-1;
    -10;-1;-1;-10;
    -10;-1;-1;-1;
    -10;-1;-1;-1;
    -10;-10;-1;-10;
    -10;-1;-10;-1;
    -10;-10;-1;-1;
    -10;-1;-10;-1;
    -10;-10;-1;-10;
    """,
    """
    -1;-1;-10;-10;
    -10;-1;-1;-10;
    -10;-1;-1;-10;
    -10;-1;-1;-10;
    -1;-10;-1;-10;
    -1;-1;-10;-10;
    -10;-1;-1;-10;
    -10;-1;-1;-10;
    -1;-1;-1;-10;
    -1;-10;-1;-10;
    -1;-1;-10;-1;
    -1;-10;-1;-10;
    -10;-1;-10;-10;
    -10;-1;-1;-10;
    -1;-10;-1;-1;
    -10;-10;-10;-1;
    -1;-1;-10;-10;
    -1;-10;-1;-10;
    -1;-10;-10;-1;
    -1;-10;-10;-1;
    -10;-10;-10;-1;
    -10;-1;-10;-1;
    -10;-1;-1;-10;
    -1;-10;-1;-10;
    -10;-1;-10;-1;
    -10;-1;-1;-10;
    -10;-10;-1;-1;
    -1;-10;-10;-1;
    -1;-10;-10;-1;
    -10;-10;-10;-1;
    -1;-1;-10;-10;
    -10;-1;-1;-10;
    -10;-1;-1;-10;
    -10;-10;-1;-1;
    -1;-10;-10;-10;
    -1;-1;-10;-10;
    -10;-1;-1;-10;
    -10;-10;-1;-1;
    -10;-1;-10;-1;
    -1;-10;-1;-10;
    -10;-1;-10;-1;
    -10;-1;-1;-10;
    -10;-10;-1;-10;
    -1;-1;-10;-10;
    -10;-1;-1;-1;
    -10;-10;-1;-1;
    -1;-1;-10;-10;
    -10;-1;-1;-10;
    -10;-1;-1;-10;
    -1;-10;-1;-1;
    -10;-1;-10;-10;
    -1;-10;-1;-10;
    -1;-1;-10;-10;
    -10;-10;-1;-1;
    -1;-10;-10;-10;
    -1;-1;-10;-10;
    -10;-1;-1;-1;
    -1;-10;-1;-10;
    -1;-1;-10;-10;
    -10;-10;-1;-1;
    -1;-1;-10;-10;
    -1;-10;-1;-1;
    -10;-1;-10;-1;
    -1;-10;-1;-10;
    -1;-10;-10;-1;
    -10;-1;-10;-1;
    -1;-10;-1;-10;
    -1;-10;-10;-1;
    -10;-1;-10;-1;
    -10;-10;-1;-10;
    -1;-10;-10;-1;
    -10;-10;-10;-1;
    -1;-1;-10;-10;
    -10;-10;-1;-1;
    -1;-1;-10;-1;
    -10;-1;-1;-10;
    -10;-10;-1;-1;
    -1;-1;-10;-1;
    -10;-1;-1;-10;
    -1;-10;-1;-10;
    -1;-1;-10;-1;
    -1;-10;-1;-10;
    -1;-10;-10;-1;
    -10;-1;-10;-10;
    -10;-10;-1;-1;
    -1;-1;-10;-10;
    -1;-10;-1;-10;
    -10;-10;-10;-1;
    -1;-1;-10;-10;
    -1;-10;-1;-1;
    -10;-10;-10;-1;
    -10;-1;-10;-1;
    -10;-1;-1;-1;
    -10;-1;-1;-10;
    -10;-1;-1;-10;
    -10;-10;-1;-1;
    -10;-1;-10;-1;
    -10;-1;-1;-10;
    -10;-10;-1;-1;
    -10;-10;-10;-1;
    """
]

In [3]:
maze_data_list_alot = [
    """
    -10;-1;-10;-10;
    -10;-1;-1;-10;
    -1;-10;-1;-10;
    -10;-1;-10;-10;
    -10;-1;-1;-10;
    -10;-1;-1;-10;
    -1;-1;-1;-10;
    -10;-1;-1;-10;
    -10;-1;-1;-10;
    -1;-10;-1;-10;
    -1;-10;-10;-10;
    -1;-1;-10;-10;
    -10;-10;-1;-1;
    -1;-1;-10;-10;
    -10;-1;-1;-10;
    -1;-10;-1;-10;
    -1;-10;-10;-1;
    -10;-1;-10;-10;
    -10;-1;-1;-10;
    -1;-10;-1;-1;
    -1;-1;-10;-1;
    -10;-10;-1;-1;
    -1;-1;-10;-10;
    -10;-1;-1;-1;
    -1;-10;-1;-10;
    -10;-1;-10;-1;
    -1;-10;-1;-1;
    -1;-1;-10;-10;
    -1;-10;-1;-10;
    -1;-10;-10;-1;
    -1;-10;-10;-1;
    -1;-10;-10;-10;
    -1;-10;-10;-1;
    -1;-10;-10;-10;
    -1;-10;-10;-1;
    -10;-1;-10;-10;
    -1;-10;-1;-1;
    -1;-10;-10;-1;
    -1;-10;-10;-1;
    -10;-10;-10;-1;
    -1;-10;-10;-1;
    -1;-10;-10;-1;
    -10;-1;-10;-1;
    -1;-10;-1;-1;
    -10;-1;-10;-1;
    -1;-10;-1;-10;
    -10;-10;-10;-1;
    -1;-10;-10;-1;
    -10;-1;-10;-1;
    -1;-10;-1;-10;
    -1;-10;-10;-1;
    -1;-1;-10;-1;
    -10;-10;-1;-10;
    -10;-1;-10;-1;
    -1;-10;-1;-10;
    -10;-1;-10;-1;
    -10;-1;-1;-10;
    -10;-1;-1;-1;
    -10;-10;-1;-10;
    -1;-10;-10;-1;
    -1;-10;-10;-1;
    -10;-1;-10;-1;
    -10;-1;-1;-10;
    -10;-1;-1;-10;
    -1;-1;-1;-1;
    -10;-1;-1;-10;
    -10;-1;-1;-10;
    -10;-10;-1;-10;
    -1;-1;-10;-10;
    -1;-10;-1;-1;
    -1;-10;-10;-1;
    -1;-1;-10;-10;
    -10;-1;-1;-10;
    -1;-10;-1;-10;
    -10;-10;-10;-1;
    -1;-1;-10;-10;
    -10;-1;-1;-10;
    -1;-10;-1;-10;
    -1;-10;-10;-1;
    -1;-10;-10;-1;
    -1;-10;-10;-1;
    -1;-10;-10;-1;
    -1;-1;-10;-10;
    -10;-10;-1;-1;
    -1;-1;-10;-10;
    -10;-10;-1;-1;
    -1;-10;-10;-10;
    -1;-10;-10;-1;
    -1;-10;-10;-1;
    -1;-10;-10;-1;
    -10;-1;-10;-1;
    -10;-10;-1;-1;
    -10;-1;-10;-1;
    -10;-1;-1;-10;
    -10;-10;-1;-1;
    -10;-1;-10;-10;
    -10;-1;-1;-1;
    -10;-1;-1;-1;
    -10;-10;-1;-1;
    -10;-10;-10;-1;
    """,
    """
    -1;-10;-10;-10;
    -1;-1;-10;-10;
    -1;-1;-1;-10;
    -10;-10;-1;-10;
    -1;-1;-10;-10;
    -1;-10;-1;-10;
    -10;-1;-10;-10;
    -1;-1;-1;-10;
    -1;-10;-1;-10;
    -1;-10;-10;-10;
    -10;-1;-10;-1;
    -10;-10;-1;-1;
    -1;-10;-10;-1;
    -10;-1;-10;-10;
    -10;-10;-1;-1;
    -10;-1;-10;-1;
    -1;-10;-1;-10;
    -1;-10;-10;-1;
    -10;-1;-10;-1;
    -10;-10;-1;-1;
    -1;-1;-10;-10;
    -10;-1;-1;-10;
    -10;-1;-1;-1;
    -1;-10;-1;-10;
    -1;-1;-10;-10;
    -10;-1;-1;-10;
    -10;-10;-1;-1;
    -1;-10;-10;-1;
    -1;-1;-10;-10;
    -1;-10;-1;-10;
    -1;-1;-10;-1;
    -1;-10;-1;-10;
    -10;-1;-10;-10;
    -1;-10;-1;-1;
    -10;-1;-10;-1;
    -10;-1;-1;-10;
    -1;-10;-1;-10;
    -10;-1;-10;-1;
    -10;-10;-1;-1;
    -1;-10;-10;-1;
    -1;-10;-10;-1;
    -10;-1;-10;-1;
    -1;-10;-1;-10;
    -1;-10;-10;-1;
    -1;-1;-10;-10;
    -1;-10;-1;-10;
    -1;-10;-10;-1;
    -1;-1;-10;-10;
    -1;-10;-1;-10;
    -1;-10;-10;-1;
    -1;-10;-10;-1;
    -1;-10;-10;-10;
    -1;-10;-10;-1;
    -10;-1;-10;-1;
    -10;-10;-1;-1;
    -1;-10;-10;-1;
    -10;-1;-10;-1;
    -10;-10;-1;-1;
    -1;-10;-10;-1;
    -1;-10;-10;-1;
    -1;-1;-10;-1;
    -10;-10;-1;-1;
    -1;-10;-10;-1;
    -1;-1;-10;-10;
    -10;-1;-1;-10;
    -10;-1;-1;-1;
    -10;-1;-1;-10;
    -10;-10;-1;-10;
    -10;-1;-10;-1;
    -1;-10;-1;-1;
    -10;-10;-10;-1;
    -1;-1;-10;-10;
    -10;-10;-1;-1;
    -10;-10;-10;-1;
    -1;-1;-10;-10;
    -10;-1;-1;-10;
    -10;-1;-1;-10;
    -10;-1;-1;-10;
    -1;-10;-1;-10;
    -1;-10;-10;-1;
    -1;-1;-10;-10;
    -10;-10;-1;-1;
    -1;-1;-10;-10;
    -1;-10;-1;-10;
    -10;-1;-10;-1;
    -10;-1;-1;-10;
    -1;-10;-1;-10;
    -1;-10;-10;-10;
    -10;-1;-10;-1;
    -10;-10;-1;-1;
    -10;-1;-10;-1;
    -10;-1;-1;-10;
    -10;-10;-1;-1;
    -10;-1;-10;-1;
    -10;-1;-1;-10;
    -10;-1;-1;-10;
    -10;-1;-1;-1;
    -10;-1;-1;-1;
    -10;-1;-1;-10;
    -10;-10;-1;-10;
    """,
    """
    -1;-1;-10;-10;
    -10;-10;-1;-10;
    -1;-1;-10;-10;
    -1;-10;-1;-10;
    -1;-1;-10;-10;
    -10;-1;-1;-10;
    -1;-1;-1;-10;
    -10;-1;-1;-10;
    -1;-10;-1;-10;
    -1;-10;-10;-10;
    -1;-10;-10;-1;
    -1;-1;-10;-10;
    -10;-10;-1;-1;
    -10;-1;-10;-1;
    -10;-1;-1;-1;
    -10;-10;-1;-10;
    -1;-10;-10;-1;
    -1;-10;-10;-10;
    -10;-1;-10;-1;
    -1;-10;-1;-1;
    -1;-10;-10;-1;
    -10;-1;-10;-1;
    -1;-10;-1;-10;
    -1;-10;-10;-10;
    -1;-1;-10;-10;
    -10;-1;-1;-10;
    -10;-10;-1;-1;
    -1;-1;-10;-1;
    -10;-10;-1;-10;
    -1;-10;-10;-1;
    -10;-1;-10;-1;
    -10;-1;-1;-10;
    -10;-1;-1;-1;
    -1;-10;-1;-1;
    -10;-1;-10;-1;
    -10;-1;-1;-10;
    -1;-10;-1;-10;
    -1;-10;-10;-1;
    -1;-1;-10;-10;
    -10;-10;-1;-1;
    -1;-1;-10;-10;
    -10;-1;-1;-10;
    -1;-10;-1;-10;
    -1;-10;-10;-1;
    -1;-1;-10;-10;
    -10;-1;-1;-10;
    -10;-10;-1;-1;
    -10;-1;-10;-1;
    -10;-1;-1;-1;
    -1;-10;-1;-10;
    -1;-10;-10;-1;
    -1;-1;-10;-10;
    -10;-10;-1;-1;
    -10;-10;-10;-1;
    -10;-1;-10;-1;
    -10;-1;-1;-10;
    -1;-10;-1;-10;
    -1;-1;-10;-10;
    -1;-10;-1;-10;
    -1;-10;-10;-1;
    -1;-10;-10;-1;
    -1;-10;-10;-1;
    -1;-1;-10;-10;
    -1;-10;-1;-10;
    -1;-1;-10;-10;
    -1;-10;-1;-10;
    -10;-1;-10;-1;
    -10;-10;-1;-1;
    -1;-10;-10;-1;
    -1;-10;-10;-1;
    -1;-10;-10;-1;
    -10;-1;-10;-1;
    -10;-10;-1;-1;
    -10;-1;-10;-1;
    -10;-10;-1;-1;
    -10;-1;-10;-1;
    -10;-1;-1;-10;
    -10;-1;-1;-10;
    -10;-10;-1;-1;
    -1;-10;-10;-1;
    -1;-1;-10;-1;
    -1;-10;-1;-10;
    -10;-1;-10;-10;
    -1;-1;-1;-10;
    -10;-10;-1;-10;
    -1;-1;-10;-10;
    -1;-10;-1;-10;
    -1;-1;-10;-10;
    -10;-1;-1;-10;
    -10;-10;-1;-1;
    -10;-10;-10;-1;
    -10;-1;-10;-1;
    -10;-10;-1;-10;
    -10;-1;-10;-1;
    -10;-1;-1;-10;
    -10;-10;-1;-1;
    -10;-1;-10;-1;
    -10;-1;-1;-1;
    -10;-1;-1;-10;
    -10;-10;-1;-10;
    """,
    """
    -1;-1;-10;-10;
    -10;-10;-1;-10;
    -1;-1;-10;-10;
    -10;-1;-1;-10;
    -10;-1;-1;-10;
    -10;-1;-1;-10;
    -10;-1;-1;-10;
    -1;-1;-1;-10;
    -1;-10;-1;-10;
    -1;-10;-10;-10;
    -1;-1;-10;-1;
    -1;-10;-1;-10;
    -1;-10;-10;-1;
    -10;-1;-10;-10;
    -1;-10;-1;-10;
    -1;-1;-10;-10;
    -10;-1;-1;-10;
    -10;-10;-1;-1;
    -10;-1;-10;-1;
    -1;-10;-1;-1;
    -1;-10;-10;-1;
    -1;-10;-10;-1;
    -10;-1;-10;-1;
    -10;-1;-1;-10;
    -1;-10;-1;-1;
    -10;-1;-10;-1;
    -10;-1;-1;-10;
    -1;-10;-1;-10;
    -1;-10;-10;-10;
    -1;-10;-10;-1;
    -1;-10;-10;-1;
    -1;-10;-10;-1;
    -1;-1;-10;-10;
    -1;-10;-1;-10;
    -1;-10;-10;-1;
    -1;-1;-10;-10;
    -10;-1;-1;-10;
    -10;-10;-1;-1;
    -1;-1;-10;-1;
    -10;-10;-1;-1;
    -1;-10;-10;-1;
    -10;-1;-10;-1;
    -10;-10;-1;-1;
    -10;-1;-10;-1;
    -10;-10;-1;-1;
    -10;-1;-10;-1;
    -10;-1;-1;-10;
    -1;-10;-1;-10;
    -10;-1;-10;-1;
    -1;-10;-1;-10;
    -1;-10;-10;-1;
    -10;-1;-10;-10;
    -1;-1;-1;-10;
    -10;-1;-1;-10;
    -1;-1;-1;-10;
    -10;-1;-1;-10;
    -10;-10;-1;-10;
    -10;-1;-10;-1;
    -1;-10;-1;-10;
    -1;-10;-10;-1;
    -10;-1;-10;-1;
    -10;-1;-1;-10;
    -10;-10;-1;-1;
    -1;-1;-10;-10;
    -10;-10;-1;-1;
    -1;-1;-10;-10;
    -10;-10;-1;-10;
    -1;-1;-10;-10;
    -10;-10;-1;-1;
    -1;-10;-10;-1;
    -1;-1;-10;-10;
    -1;-1;-1;-10;
    -1;-10;-1;-10;
    -1;-10;-10;-1;
    -1;-10;-10;-10;
    -1;-10;-10;-1;
    -10;-1;-10;-10;
    -1;-10;-1;-1;
    -1;-10;-10;-10;
    -1;-10;-10;-1;
    -1;-10;-10;-1;
    -1;-10;-10;-1;
    -10;-10;-10;-1;
    -1;-10;-10;-1;
    -1;-10;-10;-1;
    -10;-1;-10;-1;
    -1;-10;-1;-10;
    -1;-10;-10;-1;
    -1;-1;-10;-1;
    -10;-10;-1;-1;
    -10;-10;-10;-1;
    -10;-1;-10;-1;
    -10;-1;-1;-10;
    -10;-1;-1;-1;
    -10;-1;-1;-1;
    -10;-10;-1;-10;
    -10;-1;-10;-1;
    -10;-10;-1;-1;
    -10;-1;-10;-1;
    -10;-10;-1;-10;
    """,
    """
    -1;-1;-10;-10;
    -10;-1;-1;-10;
    -10;-1;-1;-10;
    -10;-1;-1;-10;
    -1;-10;-1;-10;
    -1;-1;-10;-10;
    -10;-1;-1;-10;
    -10;-1;-1;-10;
    -1;-1;-1;-10;
    -1;-10;-1;-10;
    -1;-1;-10;-1;
    -1;-10;-1;-10;
    -10;-1;-10;-10;
    -10;-1;-1;-10;
    -1;-10;-1;-1;
    -10;-10;-10;-1;
    -1;-1;-10;-10;
    -1;-10;-1;-10;
    -1;-10;-10;-1;
    -1;-10;-10;-1;
    -10;-10;-10;-1;
    -10;-1;-10;-1;
    -10;-1;-1;-10;
    -1;-10;-1;-10;
    -10;-1;-10;-1;
    -10;-1;-1;-10;
    -10;-10;-1;-1;
    -1;-10;-10;-1;
    -1;-10;-10;-1;
    -10;-10;-10;-1;
    -1;-1;-10;-10;
    -10;-1;-1;-10;
    -10;-1;-1;-10;
    -10;-10;-1;-1;
    -1;-10;-10;-10;
    -1;-1;-10;-10;
    -10;-1;-1;-10;
    -10;-10;-1;-1;
    -10;-1;-10;-1;
    -1;-10;-1;-10;
    -10;-1;-10;-1;
    -10;-1;-1;-10;
    -10;-10;-1;-10;
    -1;-1;-10;-10;
    -10;-1;-1;-1;
    -10;-10;-1;-1;
    -1;-1;-10;-10;
    -10;-1;-1;-10;
    -10;-1;-1;-10;
    -1;-10;-1;-1;
    -10;-1;-10;-10;
    -1;-10;-1;-10;
    -1;-1;-10;-10;
    -10;-10;-1;-1;
    -1;-10;-10;-10;
    -1;-1;-10;-10;
    -10;-1;-1;-1;
    -1;-10;-1;-10;
    -1;-1;-10;-10;
    -10;-10;-1;-1;
    -1;-1;-10;-10;
    -1;-10;-1;-1;
    -10;-1;-10;-1;
    -1;-10;-1;-10;
    -1;-10;-10;-1;
    -10;-1;-10;-1;
    -1;-10;-1;-10;
    -1;-10;-10;-1;
    -10;-1;-10;-1;
    -10;-10;-1;-10;
    -1;-10;-10;-1;
    -10;-10;-10;-1;
    -1;-1;-10;-10;
    -10;-10;-1;-1;
    -1;-1;-10;-1;
    -10;-1;-1;-10;
    -10;-10;-1;-1;
    -1;-1;-10;-1;
    -10;-1;-1;-10;
    -1;-10;-1;-10;
    -1;-1;-10;-1;
    -1;-10;-1;-10;
    -1;-10;-10;-1;
    -10;-1;-10;-10;
    -10;-10;-1;-1;
    -1;-1;-10;-10;
    -1;-10;-1;-10;
    -10;-10;-10;-1;
    -1;-1;-10;-10;
    -1;-10;-1;-1;
    -10;-10;-10;-1;
    -10;-1;-10;-1;
    -10;-1;-1;-1;
    -10;-1;-1;-10;
    -10;-1;-1;-10;
    -10;-10;-1;-1;
    -10;-1;-10;-1;
    -10;-1;-1;-10;
    -10;-10;-1;-1;
    -10;-10;-10;-1;
    """,
#     """
#     -1;-1;-10;-10;
# -10;-1;-1;-10;
# -10;-1;-1;-10;
# -10;-1;-1;-10;
# -1;-10;-1;-10;
# -1;-1;-10;-10;
# -1;-10;-1;-10;
# -1;-1;-10;-10;
# -10;-1;-1;-10;
# -1;-10;-1;-10;
# -1;-10;-10;-1;
# -1;-1;-10;-10;
# -10;-1;-1;-10;
# -1;-10;-1;-10;
# -10;-1;-10;-1;
# -10;-10;-1;-1;
# -10;-1;-10;-1;
# -10;-10;-1;-1;
# -1;-1;-10;-10;
# -10;-10;-1;-1;
# -1;-10;-10;-1;
# -10;-1;-10;-1;
# -1;-10;-1;-10;
# -1;-1;-10;-1;
# -1;-10;-1;-10;
# -1;-1;-10;-10;
# -10;-1;-1;-10;
# -1;-10;-1;-10;
# -10;-1;-10;-1;
# -10;-10;-1;-10;
# -10;-1;-10;-1;
# -1;-10;-1;-10;
# -10;-10;-10;-1;
# -1;-10;-10;-1;
# -10;-1;-10;-1;
# -10;-10;-1;-1;
# -1;-10;-10;-10;
# -1;-10;-10;-1;
# -1;-1;-10;-10;
# -1;-10;-1;-10;
# -1;-10;-10;-10;
# -1;-10;-10;-1;
# -1;-1;-10;-10;
# -10;-10;-1;-1;
# -1;-10;-10;-10;
# -1;-1;-10;-10;
# -10;-1;-1;-1;
# -10;-10;-1;-1;
# -1;-10;-10;-1;
# -1;-10;-10;-1;
# -1;-10;-10;-1;
# -10;-1;-10;-1;
# -10;-10;-1;-1;
# -1;-1;-10;-10;
# -10;-1;-1;-1;
# -10;-10;-1;-1;
# -1;-1;-10;-10;
# -10;-1;-1;-10;
# -1;-10;-1;-1;
# -10;-10;-10;-1;
# -1;-1;-10;-1;
# -10;-1;-1;-10;
# -10;-10;-1;-10;
# -10;-1;-10;-1;
# -1;-10;-1;-10;
# -1;-1;-10;-10;
# -10;-1;-1;-1;
# -10;-10;-1;-10;
# -10;-1;-10;-1;
# -1;-10;-1;-10;
# -1;-1;-10;-1;
# -10;-1;-1;-10;
# -1;-10;-1;-10;
# -1;-1;-10;-10;
# -10;-10;-1;-1;
# -10;-10;-10;-1;
# -1;-1;-10;-10;
# -10;-1;-1;-10;
# -1;-10;-1;-10;
# -1;-10;-10;-1;
# -1;-10;-10;-1;
# -1;-1;-10;-10;
# -10;-10;-1;-1;
# -1;-10;-10;-1;
# -10;-1;-10;-10;
# -1;-1;-1;-10;
# -10;-10;-1;-1;
# -1;-1;-10;-10;
# -10;-10;-1;-1;
# -1;-10;-10;-1;
# -10;-10;-10;-1;
# -10;-1;-10;-1;
# -10;-1;-1;-10;
# -10;-1;-1;-1;
# -10;-1;-1;-10;
# -10;-10;-1;-1;
# -10;-1;-10;-10;
# -10;-1;-1;-1;
# -10;-1;-1;-10;
# -10;-10;-1;-1;
#     """,
# """
# -1;-1;-10;-10;
# -1;-10;-1;-10;
# -1;-10;-10;-10;
# -1;-1;-10;-10;
# -10;-1;-1;-10;
# -10;-1;-1;-10;
# -1;-1;-1;-10;
# -10;-10;-1;-10;
# -1;-1;-10;-10;
# -1;-10;-1;-10;
# -1;-10;-10;-1;
# -1;-10;-10;-1;
# -1;-10;-10;-1;
# -10;-1;-10;-1;
# -1;-10;-1;-10;
# -1;-10;-10;-10;
# -10;-1;-10;-1;
# -1;-10;-1;-10;
# -1;-10;-10;-1;
# -1;-10;-10;-1;
# -1;-10;-10;-1;
# -1;-10;-10;-1;
# -1;-1;-10;-1;
# -1;-10;-1;-10;
# -1;-10;-10;-1;
# -1;-1;-10;-1;
# -1;-10;-1;-10;
# -10;-1;-10;-1;
# -10;-10;-1;-1;
# -1;-10;-10;-1;
# -1;-10;-10;-1;
# -10;-1;-10;-1;
# -10;-10;-1;-1;
# -1;-10;-10;-1;
# -1;-10;-10;-1;
# -1;-10;-10;-1;
# -10;-10;-10;-1;
# -1;-1;-10;-10;
# -10;-1;-1;-10;
# -1;-10;-1;-1;
# -1;-10;-10;-1;
# -1;-1;-10;-10;
# -1;-10;-1;-10;
# -10;-10;-10;-1;
# -1;-10;-10;-1;
# -10;-1;-10;-1;
# -1;-10;-1;-10;
# -1;-10;-10;-1;
# -10;-1;-10;-10;
# -1;-10;-1;-1;
# -1;-1;-10;-1;
# -10;-10;-1;-1;
# -1;-10;-10;-1;
# -1;-1;-10;-10;
# -10;-10;-1;-1;
# -1;-1;-10;-10;
# -10;-10;-1;-1;
# -1;-10;-10;-1;
# -1;-10;-10;-10;
# -1;-10;-10;-1;
# -1;-1;-10;-1;
# -10;-10;-1;-10;
# -1;-10;-10;-1;
# -10;-1;-10;-1;
# -1;-1;-1;-10;
# -10;-10;-1;-1;
# -1;-1;-10;-10;
# -1;-10;-1;-1;
# -1;-10;-10;-1;
# -1;-10;-10;-1;
# -1;-10;-10;-1;
# -1;-1;-10;-10;
# -10;-10;-1;-1;
# -1;-1;-10;-10;
# -10;-10;-1;-1;
# -1;-1;-10;-10;
# -10;-10;-1;-1;
# -10;-10;-10;-1;
# -1;-10;-10;-1;
# -1;-10;-10;-1;
# -1;-10;-10;-1;
# -10;-1;-10;-1;
# -1;-10;-1;-10;
# -1;-10;-10;-1;
# -1;-10;-10;-10;
# -10;-1;-10;-1;
# -10;-1;-1;-10;
# -1;-10;-1;-10;
# -1;-10;-10;-1;
# -1;-10;-10;-1;
# -10;-1;-10;-1;
# -10;-10;-1;-10;
# -10;-1;-10;-1;
# -10;-1;-1;-1;
# -10;-1;-1;-1;
# -10;-1;-1;-10;
# -10;-10;-1;-10;
# -10;-1;-10;-1;
# -10;-10;-1;-1;
# -10;-10;-10;-1;
# """,
# """
# -1;-1;-10;-10;
# -1;-1;-1;-10;
# -10;-1;-1;-10;
# -10;-1;-1;-10;
# -10;-1;-1;-10;
# -1;-10;-1;-10;
# -1;-1;-10;-10;
# -10;-1;-1;-10;
# -1;-10;-1;-10;
# -1;-10;-10;-10;
# -1;-10;-10;-1;
# -10;-1;-10;-1;
# -1;-10;-1;-10;
# -1;-1;-10;-10;
# -10;-10;-1;-10;
# -10;-1;-10;-1;
# -10;-10;-1;-1;
# -1;-1;-10;-10;
# -10;-10;-1;-1;
# -1;-10;-10;-1;
# -10;-10;-10;-1;
# -1;-1;-10;-10;
# -10;-10;-1;-1;
# -1;-10;-10;-1;
# -1;-1;-10;-10;
# -10;-1;-1;-10;
# -1;-10;-1;-10;
# -10;-1;-10;-1;
# -10;-1;-1;-10;
# -1;-10;-1;-1;
# -1;-1;-10;-10;
# -10;-10;-1;-1;
# -10;-1;-10;-10;
# -1;-1;-1;-1;
# -10;-10;-1;-1;
# -1;-10;-10;-10;
# -1;-1;-10;-1;
# -1;-1;-1;-10;
# -10;-10;-1;-10;
# -1;-10;-10;-1;
# -10;-1;-10;-1;
# -10;-1;-1;-10;
# -1;-10;-1;-10;
# -10;-1;-10;-1;
# -1;-10;-1;-10;
# -1;-10;-10;-1;
# -1;-10;-10;-1;
# -1;-10;-10;-1;
# -1;-1;-10;-10;
# -10;-10;-1;-1;
# -1;-1;-10;-10;
# -10;-10;-1;-10;
# -1;-10;-10;-1;
# -10;-1;-10;-10;
# -10;-1;-1;-1;
# -10;-10;-1;-1;
# -1;-10;-10;-1;
# -1;-10;-10;-1;
# -1;-10;-10;-1;
# -1;-10;-10;-10;
# -10;-1;-10;-1;
# -1;-10;-1;-10;
# -1;-10;-10;-1;
# -1;-1;-10;-10;
# -10;-1;-1;-10;
# -10;-1;-1;-10;
# -1;-10;-1;-1;
# -10;-10;-10;-1;
# -1;-10;-10;-1;
# -1;-10;-10;-1;
# -1;-10;-10;-10;
# -10;-1;-10;-1;
# -10;-10;-1;-1;
# -1;-10;-10;-1;
# -10;-1;-10;-10;
# -10;-1;-1;-10;
# -1;-10;-1;-1;
# -1;-1;-10;-10;
# -10;-10;-1;-1;
# -1;-10;-10;-1;
# -1;-1;-10;-1;
# -1;-10;-1;-10;
# -1;-1;-10;-10;
# -1;-10;-1;-1;
# -1;-1;-10;-10;
# -1;-10;-1;-10;
# -10;-10;-10;-1;
# -10;-1;-10;-1;
# -10;-1;-1;-10;
# -1;-10;-1;-1;
# -10;-10;-10;-1;
# -10;-1;-10;-1;
# -10;-10;-1;-1;
# -10;-1;-10;-1;
# -10;-10;-1;-1;
# -10;-1;-10;-1;
# -10;-1;-1;-10;
# -10;-1;-1;-10;
# -10;-1;-1;-10;
# -10;-10;-1;-1;
# """,
# """
# -10;-1;-10;-10;
# -1;-1;-1;-10;
# -1;-10;-1;-10;
# -1;-1;-10;-10;
# -1;-10;-1;-10;
# -1;-1;-10;-10;
# -1;-1;-1;-10;
# -10;-1;-1;-10;
# -1;-10;-1;-10;
# -1;-10;-10;-10;
# -1;-1;-10;-10;
# -10;-10;-1;-1;
# -10;-1;-10;-1;
# -10;-10;-1;-1;
# -10;-10;-10;-1;
# -1;-10;-10;-1;
# -10;-1;-10;-1;
# -1;-10;-1;-10;
# -10;-1;-10;-1;
# -1;-10;-1;-1;
# -1;-10;-10;-1;
# -1;-1;-10;-10;
# -10;-1;-1;-10;
# -10;-1;-1;-10;
# -10;-1;-1;-10;
# -10;-1;-1;-1;
# -10;-10;-1;-10;
# -1;-10;-10;-1;
# -1;-10;-10;-10;
# -1;-10;-10;-1;
# -1;-10;-10;-1;
# -1;-10;-10;-1;
# -1;-10;-10;-10;
# -1;-1;-10;-10;
# -10;-1;-1;-10;
# -10;-1;-1;-10;
# -10;-1;-1;-10;
# -10;-10;-1;-1;
# -1;-10;-10;-1;
# -1;-10;-10;-1;
# -1;-1;-10;-1;
# -10;-10;-1;-1;
# -1;-10;-10;-1;
# -10;-1;-10;-1;
# -1;-10;-1;-10;
# -1;-1;-10;-10;
# -10;-1;-1;-10;
# -10;-10;-1;-10;
# -1;-1;-10;-1;
# -10;-10;-1;-1;
# -10;-1;-10;-1;
# -10;-1;-1;-10;
# -1;-10;-1;-1;
# -1;-1;-10;-10;
# -10;-10;-1;-1;
# -10;-1;-10;-1;
# -1;-10;-1;-10;
# -10;-1;-10;-10;
# -10;-1;-1;-1;
# -1;-10;-1;-10;
# -10;-1;-10;-10;
# -1;-10;-1;-10;
# -1;-10;-10;-1;
# -10;-1;-10;-1;
# -1;-1;-1;-10;
# -10;-10;-1;-10;
# -10;-1;-10;-1;
# -1;-10;-1;-10;
# -10;-1;-10;-10;
# -1;-10;-1;-1;
# -1;-1;-10;-10;
# -1;-10;-1;-1;
# -10;-1;-10;-1;
# -1;-10;-1;-10;
# -10;-1;-10;-1;
# -1;-1;-1;-10;
# -1;-10;-1;-10;
# -10;-1;-10;-1;
# -1;-10;-1;-10;
# -10;-10;-10;-1;
# -1;-10;-10;-1;
# -10;-10;-10;-1;
# -1;-1;-10;-10;
# -10;-10;-1;-1;
# -1;-10;-10;-10;
# -1;-10;-10;-1;
# -10;-1;-10;-1;
# -10;-10;-1;-10;
# -10;-1;-10;-1;
# -1;-10;-1;-10;
# -10;-1;-10;-1;
# -10;-1;-1;-10;
# -10;-1;-1;-1;
# -10;-1;-1;-10;
# -10;-10;-1;-1;
# -10;-1;-10;-1;
# -10;-1;-1;-10;
# -10;-1;-1;-10;
# -10;-1;-1;-10;
# -10;-10;-1;-1;
# """,
# """
# -1;-10;-10;-10;
# -1;-1;-10;-10;
# -10;-1;-1;-10;
# -1;-1;-1;-10;
# -1;-10;-1;-10;
# -1;-1;-10;-10;
# -10;-1;-1;-10;
# -1;-10;-1;-10;
# -10;-1;-10;-10;
# -1;-10;-1;-10;
# -1;-1;-10;-1;
# -10;-1;-1;-1;
# -10;-10;-1;-10;
# -1;-10;-10;-1;
# -10;-1;-10;-1;
# -10;-10;-1;-1;
# -1;-10;-10;-10;
# -10;-1;-10;-1;
# -1;-10;-1;-10;
# -1;-10;-10;-1;
# -10;-10;-10;-1;
# -1;-1;-10;-10;
# -1;-10;-1;-10;
# -1;-10;-10;-1;
# -10;-1;-10;-10;
# -1;-1;-1;-10;
# -1;-10;-1;-1;
# -1;-1;-10;-10;
# -10;-10;-1;-1;
# -1;-10;-10;-1;
# -1;-1;-10;-10;
# -10;-10;-1;-1;
# -1;-10;-10;-1;
# -10;-1;-10;-1;
# -1;-10;-1;-10;
# -1;-10;-10;-1;
# -10;-1;-10;-1;
# -10;-10;-1;-1;
# -10;-1;-10;-10;
# -1;-10;-1;-1;
# -10;-1;-10;-1;
# -10;-10;-1;-10;
# -1;-10;-10;-1;
# -1;-1;-10;-10;
# -10;-10;-1;-1;
# -10;-1;-10;-1;
# -10;-1;-1;-10;
# -10;-1;-1;-10;
# -10;-1;-1;-10;
# -1;-10;-1;-1;
# -1;-1;-10;-10;
# -10;-1;-1;-10;
# -10;-10;-1;-1;
# -10;-1;-10;-1;
# -10;-1;-1;-10;
# -10;-1;-1;-10;
# -10;-1;-1;-10;
# -1;-1;-1;-10;
# -1;-10;-1;-10;
# -10;-10;-10;-1;
# -1;-10;-10;-1;
# -1;-1;-10;-10;
# -10;-1;-1;-10;
# -1;-1;-1;-10;
# -10;-1;-1;-10;
# -10;-1;-1;-10;
# -1;-10;-1;-10;
# -1;-10;-10;-1;
# -10;-1;-10;-1;
# -1;-10;-1;-10;
# -1;-10;-10;-1;
# -10;-1;-10;-1;
# -10;-10;-1;-10;
# -1;-10;-10;-1;
# -1;-1;-10;-10;
# -1;-10;-1;-10;
# -1;-10;-10;-1;
# -10;-1;-10;-1;
# -10;-10;-1;-10;
# -1;-10;-10;-1;
# -10;-1;-10;-1;
# -10;-1;-1;-10;
# -10;-1;-1;-10;
# -10;-10;-1;-1;
# -1;-10;-10;-1;
# -10;-10;-10;-1;
# -1;-10;-10;-1;
# -1;-1;-10;-10;
# -10;-1;-1;-10;
# -1;-10;-1;-1;
# -10;-1;-10;-10;
# -10;-1;-1;-10;
# -10;-1;-1;-10;
# -10;-1;-1;-10;
# -10;-1;-1;-1;
# -10;-1;-1;-10;
# -10;-1;-1;-1;
# -10;-10;-1;-1;
# -10;-1;-10;-10;
# -10;-10;-1;-1;
# """
]

In [4]:
import gymnasium as gym
from gymnasium import spaces
import numpy as np
from PIL import Image, ImageDraw

class CustomMazeEnvCNNIMGML(gym.Env):
    def __init__(self, max_steps_per_episode=100, maze_data_list=None, maze_size=10, random_start=False):
        super(CustomMazeEnvCNNIMGML, self).__init__()
        
        self.maze_size = maze_size
        self.max_steps_per_episode = max_steps_per_episode
        self.action_space = spaces.Discrete(4)  # [0: up, 1: right, 2: down, 3: left]
        
        # Define image size for DQN
        self.image_size = 84
        self.observation_space = spaces.Box(low=0, high=255, shape=(self.image_size, self.image_size, 3), dtype=np.uint8)

        self.mazes = []
        self.current_maze_index = 0
        self.random_start = random_start
        self.episode = 0
        
        self.reward = 0
        self.done = False
        self.is_success = False
        
        self.state = None
        self.start = None
        self.goal = (self.maze_size - 1, self.maze_size - 1)

        self.visit_counts = np.zeros((self.maze_size, self.maze_size), dtype=np.int32)
        self.current_step = 0

        for maze_data in maze_data_list:
            self.mazes.append(self.initialize_maze(maze_data))
        
        self.maze = self.mazes[self.current_maze_index]
        
        
    def initialize_maze(self, input_string):
        maze_size = self.maze_size
        rows = input_string.strip().split('\n')
        top_wall = np.zeros((maze_size, maze_size), dtype=np.uint8)
        right_wall = np.zeros((maze_size, maze_size), dtype=np.uint8)
        bottom_wall = np.zeros((maze_size, maze_size), dtype=np.uint8)
        left_wall = np.zeros((maze_size, maze_size), dtype=np.uint8)

        parsed_data = []
        for row in rows:
            parsed_data.append([int(x) for x in row.split(';') if x != ''])

        for i in range(maze_size):
            for j in range(maze_size):
                state_index = i * maze_size + j
                actions = parsed_data[state_index]
                bottom_wall[i, j] = 1 if actions[0] == -10 else 0
                right_wall[i, j] = 1 if actions[1] == -10 else 0
                left_wall[i, j] = 1 if actions[2] == -10 else 0
                top_wall[i, j] = 1 if actions[3] == -10 else 0

        return np.stack([top_wall, right_wall, bottom_wall, left_wall], axis=0)
        
    def _get_obs(self):
        return self._render_maze()

    def reset(self, seed=42, options=None):
        new_seed = seed + self.episode
        super().reset(seed=new_seed)
        self.episode += 1

        if not self.random_start:
            self.start = (0, 0)
        else:
            self.start = (self.np_random.integers(0, self.maze_size), self.np_random.integers(0, self.maze_size))
        
        self.current_step = 0
        self.state = self.start
        self.visit_counts[self.state] += 1
        
        # Change to the next maze
        self.current_maze_index = (self.current_maze_index + 1) % len(self.mazes)
        self.maze = self.mazes[self.current_maze_index]
        return self._get_obs(), {}

    def step(self, action):
        self.current_step += 1
        x, y = self.state
        new_x, new_y = x, y

        # Define possible moves
        if action == 0:  # up
            new_x = max(0, x - 1)
        elif action == 1:  # right
            new_y = min(self.maze_size - 1, y + 1)
        elif action == 2:  # down
            new_x = min(self.maze_size - 1, x + 1)
        elif action == 3:  # left
            new_y = max(0, y - 1)

        # Check for walls or boundaries
        wall_hit = False
        if action == 0 and (x == 0 or self.maze[0, x, y] == 1):  # Top wall or top edge
            wall_hit = True
        elif action == 1 and (y == self.maze_size - 1 or self.maze[1, x, y] == 1):  # Right wall or right edge
            wall_hit = True
        elif action == 2 and (x == self.maze_size - 1 or self.maze[2, x, y] == 1):  # Bottom wall or bottom edge
            wall_hit = True
        elif action == 3 and (y == 0 or self.maze[3, x, y] == 1):  # Left wall or left edge
            wall_hit = True
        
        
        # Determine reward and update state
        if wall_hit:
            self.reward = -10
        else:
            self.state = (new_x, new_y)
            if self.state == self.goal:
                self.reward = 10
            else:
                self.reward = -1  # Default step cost
        
        self.visit_counts[self.state] += 1

        # Check if goal is reached or max steps are reached
        self.done = False
        self.is_success = False
        if self.state == self.goal:
            self.done = True
            self.is_success = True
        elif self.current_step >= self.max_steps_per_episode:
            self.done = True
            self.is_success = False
        
        return self._get_obs(), self.reward, self.done, False, {"is_success": self.is_success}

    
    def _render_maze(self):
        img = Image.new('RGB', (self.image_size, self.image_size), color=(255, 255, 255))
        draw = ImageDraw.Draw(img)

        cell_size = min(self.image_size // self.maze_size, self.image_size // self.maze_size)
        maze_pixel_size = cell_size * self.maze_size
        offset_x = (self.image_size - maze_pixel_size) // 2
        offset_y = (self.image_size - maze_pixel_size) // 2

        # Draw the maze walls
        for i in range(self.maze_size):
            for j in range(self.maze_size):
                x, y = offset_x + j * cell_size, offset_y + i * cell_size
                walls = [(0, [(x, y), (x + cell_size, y)]),             # Top
                        (1, [(x + cell_size, y), (x + cell_size, y + cell_size)]),  # Right
                        (2, [(x, y + cell_size), (x + cell_size, y + cell_size)]),  # Bottom
                        (3, [(x, y), (x, y + cell_size)])]            # Left
                for idx, line in walls:
                    if self.maze[idx, i, j]:
                        draw.line(line, fill=(0, 0, 0), width=1)

        # Function to draw centered cells
        def draw_centered_cell(x, y, color, size_factor=0.6):
            size = int(cell_size * size_factor)
            center_x = x + cell_size // 2
            center_y = y + cell_size // 2
            top_left_x = center_x - size // 2
            top_left_y = center_y - size // 2
            draw.rectangle([top_left_x, top_left_y, 
                            top_left_x + size, top_left_y + size], 
                        fill=color)

        # Draw start (green), goal (red), and agent (blue)
        start_x, start_y = offset_x + self.start[1] * cell_size, offset_y + self.start[0] * cell_size
        goal_x, goal_y = offset_x + self.goal[1] * cell_size, offset_y + self.goal[0] * cell_size
        agent_x, agent_y = offset_x + self.state[1] * cell_size, offset_y + self.state[0] * cell_size

        draw_centered_cell(start_x, start_y, (0, 255, 0))  # Green start
        draw_centered_cell(goal_x, goal_y, (255, 0, 0))    # Red goal
        
        # Draw agent as a centered circle
        agent_size = int(cell_size * 0.4)
        center_x = agent_x + cell_size // 2
        center_y = agent_y + cell_size // 2
        top_left_x = center_x - agent_size // 2
        top_left_y = center_y - agent_size // 2
        draw.ellipse([top_left_x, top_left_y, 
                    top_left_x + agent_size, top_left_y + agent_size], 
                    fill=(0, 0, 255))  # Blue agent

        return np.array(img)

    def render(self, mode='human'):
        img = self._render_maze()
        if mode == 'human':
            Image.fromarray(img).show()
        elif mode == 'rgb_array':
            return img

In [5]:
import gymnasium as gym
from gymnasium import spaces
import numpy as np

class CustomMazeEnvMlpImprovedML(gym.Env):
    def __init__(self, max_steps_per_episode=100, maze_data_list=None, maze_size=10, random_start=False):
        super(CustomMazeEnvMlpImprovedML, self).__init__()
        
        
        # Define the size of the maze
        self.maze_size = maze_size
        self.max_steps_per_episode = max_steps_per_episode
        
        # Define action and observation space
        self.action_space = spaces.Discrete(4)  # [0: up, 1: right, 2: down, 3: left]
        self.observation_space = spaces.Box(low=0, high=127, shape=(self.maze_size * self.maze_size,), dtype=np.uint8)

        self.mazes = []
        self.current_maze_index = 0
        self.random_start = random_start
        self.episode = 0
        
        self.reward = 0
        self.done = False
        self.is_success = False

        # Initial state
        self.state = None
        self.start = None
        self.goal = (self.maze_size - 1, self.maze_size - 1)

        # Initialize visit counts
        self.visit_counts = np.zeros((self.maze_size, self.maze_size), dtype=np.int32)
        self.current_step = 0
        
        for maze_data in maze_data_list:
            self.mazes.append(self.initialize_maze(maze_data))
        
        self.maze = self.mazes[self.current_maze_index]
        

    def initialize_maze(self, input_string):
        rows = input_string.strip().split('\n')
        maze = np.zeros(self.maze_size * self.maze_size, dtype=np.uint8)

        parsed_data = []
        for row in rows:
            parsed_data.append([int(x) for x in row.split(';') if x != ''])

        for i in range(self.maze_size):
            for j in range(self.maze_size):
                state_index = i * self.maze_size + j
                actions = parsed_data[state_index]
                
                state = 0
                state |= (1 if actions[3] == -10 else 0)  # Top wall
                state |= (1 if actions[1] == -10 else 0) << 1  # Right wall
                state |= (1 if actions[0] == -10 else 0) << 2  # Bottom wall
                state |= (1 if actions[2] == -10 else 0) << 3  # Left wall
                state |= (1 if (i, j) == self.start else 0) << 4  # Start position
                state |= (1 if (i, j) == self.goal else 0) << 5  # Goal position
                
                maze[state_index] = state

        return maze

    def _get_obs(self):
        obs = self.maze.copy()
        x, y = self.state
        obs[x * self.maze_size + y] |= 1 << 6  # Set the agent bit
        return obs

    def reset(self, seed=42, options=None):
        new_seed = seed + self.episode
        super().reset(seed=new_seed)
        self.episode += 1

        if not self.random_start:
            self.start = (0, 0)
        else:
            self.start = (self.np_random.integers(0, self.maze_size), self.np_random.integers(0, self.maze_size))
        
        self.current_step = 0
        self.state = self.start
        self.visit_counts[self.state] += 1
        
        self.current_maze_index = (self.current_maze_index + 1) % len(self.mazes)
        self.maze = self.mazes[self.current_maze_index]
        return self._get_obs(), {}

    def step(self, action):
        self.current_step += 1
        x, y = self.state
        new_x, new_y = x, y

        # Define possible moves
        if action == 0:  # up
            new_x = max(0, x - 1)
        elif action == 1:  # right
            new_y = min(self.maze_size - 1, y + 1)
        elif action == 2:  # down
            new_x = min(self.maze_size - 1, x + 1)
        elif action == 3:  # left
            new_y = max(0, y - 1)

        state_index = x * self.maze_size + y

        # Check for walls
        wall_hit = False
        if action == 0 and (x == 0 or self.maze[state_index] & 1):  # Top wall
            wall_hit = True
        elif action == 1 and (y == self.maze_size - 1 or self.maze[state_index] & (1 << 1)):  # Right wall
            wall_hit = True
        elif action == 2 and (x == self.maze_size - 1 or self.maze[state_index] & (1 << 2)):  # Bottom wall
            wall_hit = True
        elif action == 3 and (y == 0 or self.maze[state_index] & (1 << 3)):  # Left wall
            wall_hit = True
        
        # Determine reward and update state
        if wall_hit:
            self.reward = -10
        else:
            self.state = (new_x, new_y)
            if self.state == self.goal:
                self.reward = 10
            else:
                self.reward = -1  # Default step cost
        
        self.visit_counts[self.state] += 1

        # Check if goal is reached or max steps are reached
        self.done = False
        self.is_success = False
        truncated = False
        if self.state == self.goal:
            self.done = True
            self.is_success = True
        elif self.current_step >= self.max_steps_per_episode:
            self.done = True
            self.is_success = False
            truncated = True
        
        return self._get_obs(), self.reward, self.done, truncated, {"is_success": self.is_success}
    
    def render(self, mode='human'):
        maze_render = np.full((self.maze_size * 2 + 1, self.maze_size * 2 + 1), ' ', dtype=str)
        
        # Draw walls
        for i in range(self.maze_size):
            for j in range(self.maze_size):
                cell_y, cell_x = i * 2 + 1, j * 2 + 1
                state_index = i * self.maze_size + j
                state = self.maze[state_index]
                
                if state & 1:  # Top wall
                    maze_render[cell_y - 1, cell_x] = '─'
                if state & (1 << 1):  # Right wall
                    maze_render[cell_y, cell_x + 1] = '│'
                if state & (1 << 2):  # Bottom wall
                    maze_render[cell_y + 1, cell_x] = '─'
                if state & (1 << 3):  # Left wall
                    maze_render[cell_y, cell_x - 1] = '│'

        # Mark start, goal, and current position
        start_y, start_x = 1, 1
        goal_y, goal_x = self.maze_size * 2 - 1, self.maze_size * 2 - 1
        agent_y, agent_x = self.state[0] * 2 + 1, self.state[1] * 2 + 1

        maze_render[start_y, start_x] = 'S'
        maze_render[goal_y, goal_x] = 'G'
        maze_render[agent_y, agent_x] = 'A'

        # Print the maze
        for row in maze_render:
            print(''.join(row))
        print("\n")

In [6]:
import gymnasium as gym
from gymnasium import spaces
import numpy as np

class CustomMazeEnvCnnML(gym.Env):
    def __init__(self, max_steps_per_episode=100, maze_data_list=None, maze_size=10, random_start=False):
        super(CustomMazeEnvCnnML, self).__init__()
        
        # Define the size of the maze
        self.maze_size = maze_size
        self.max_steps_per_episode = max_steps_per_episode
            
        # Define action and observation space
        self.action_space = spaces.Discrete(4)  # [0: up, 1: right, 2: down, 3: left]
        self.observation_space = spaces.Box(low=0, high=127, shape=(1, self.maze_size, self.maze_size), dtype=np.uint8)

        self.mazes = []
        self.current_maze_index = 0
        self.random_start = random_start
        self.episode = 0
        
        self.reward = 0
        self.done = False
        self.is_success = False

        # Initial state
        self.state = None
        self.start = None
        self.goal = (self.maze_size - 1, self.maze_size - 1)
        
        self.visit_counts = np.zeros((self.maze_size, self.maze_size), dtype=np.int32)
        self.current_step = 0

        for maze_data in maze_data_list:
            self.mazes.append(self.initialize_maze(maze_data))
        
        self.maze = self.mazes[self.current_maze_index]
        
    def initialize_maze(self, input_string):
        maze_size = self.maze_size
        rows = input_string.strip().split('\n')

        maze = np.zeros((maze_size, maze_size), dtype=np.uint8)

        parsed_data = []
        for row in rows:
            parsed_data.append([int(x) for x in row.split(';') if x != ''])

        for i in range(maze_size):
            for j in range(maze_size):
                state_index = i * maze_size + j
                actions = parsed_data[state_index]
                
                state = 0
                state |= (1 if actions[3] == -10 else 0)  # Top wall
                state |= (1 if actions[1] == -10 else 0) << 1  # Right wall
                state |= (1 if actions[0] == -10 else 0) << 2  # Bottom wall
                state |= (1 if actions[2] == -10 else 0) << 3  # Left wall
                state |= (1 if (i, j) == self.start else 0) << 4  # Start position
                state |= (1 if (i, j) == self.goal else 0) << 5  # Goal position
                
                maze[i, j] = state
        
        return maze
        
    def _get_obs(self):
        obs = self.maze.copy()
        agent_x, agent_y = self.state
        obs[agent_x, agent_y] |= 1 << 6  # Set the agent bit
        return obs

    def reset(self, seed=42, options=None):
        new_seed = seed + self.episode
        super().reset(seed=new_seed)
        self.episode += 1

        if not self.random_start:
            self.start = (0, 0)
        else:
            self.start = (self.np_random.integers(0, self.maze_size), self.np_random.integers(0, self.maze_size))
        
        self.current_step = 0
        self.state = self.start
        self.visit_counts[self.state] += 1
        
        self.current_maze_index = (self.current_maze_index + 1) % len(self.mazes)
        self.maze = self.mazes[self.current_maze_index]
        return self._get_obs(), {}

    def step(self, action):
        self.current_step += 1
        x, y = self.state
        new_x, new_y = x, y

        # Define possible moves
        if action == 0:  # up
            new_x = max(0, x - 1)
        elif action == 1:  # right
            new_y = min(self.maze_size - 1, y + 1)
        elif action == 2:  # down
            new_x = min(self.maze_size - 1, x + 1)
        elif action == 3:  # left
            new_y = max(0, y - 1)

        # Check for walls or boundaries
        wall_hit = False
        if action == 0 and (x == 0 or self.maze[x, y] & 1):  # Top wall or top edge
            wall_hit = True
        elif action == 1 and (y == self.maze_size - 1 or self.maze[x, y] & (1 << 1)):  # Right wall or right edge
            wall_hit = True
        elif action == 2 and (x == self.maze_size - 1 or self.maze[x, y] & (1 << 2)):  # Bottom wall or bottom edge
            wall_hit = True
        elif action == 3 and (y == 0 or self.maze[x, y] & (1 << 3)):  # Left wall or left edge
            wall_hit = True
        
        # Determine reward and update state
        if wall_hit:
            self.reward = -10
        else:
            self.state = (new_x, new_y)
            if self.state == self.goal:
                self.reward = 10
            else:
                self.reward = -1  # Default step cost
        
        self.visit_counts[self.state] += 1

        # Check if goal is reached or max steps are reached
        self.done = False
        self.is_success = False
        if self.state == self.goal:
            self.done = True
            self.is_success = True
        elif self.current_step >= self.max_steps_per_episode:
            self.done = True
            self.is_success = False
        
        return self._get_obs(), self.reward, self.done, False, {"is_success": self.is_success}

    
    def _state_to_binary(self, state):
        return f"{state:07b}"

    def render_binary(self):
        for i in range(self.maze_size):
            for j in range(self.maze_size):
                state = self.maze[i, j]
                if self.state == (i, j):
                    state |= 1 << 6  # Set agent bit if it's the current position
                binary = self._state_to_binary(state)
                print(f"{binary} ", end="")
            print()  # New line after each row
        print()  # Empty line at the end

    def render(self, mode='human'):
        maze_render = np.full((self.maze_size * 2 + 1, self.maze_size * 2 + 1), ' ', dtype=str)
        
        # Draw walls
        for i in range(self.maze_size):
            for j in range(self.maze_size):
                cell_y, cell_x = i * 2 + 1, j * 2 + 1
                cell_state = self.maze[i, j]
                if cell_state & 1:  # Top wall
                    maze_render[cell_y - 1, cell_x] = '─'
                if cell_state & (1 << 1):  # Right wall
                    maze_render[cell_y, cell_x + 1] = '│'
                if cell_state & (1 << 2):  # Bottom wall
                    maze_render[cell_y + 1, cell_x] = '─'
                if cell_state & (1 << 3):  # Left wall
                    maze_render[cell_y, cell_x - 1] = '│'

        # Mark start, goal, and current position
        start_y, start_x = 1, 1
        goal_y, goal_x = self.maze_size * 2 - 1, self.maze_size * 2 - 1
        agent_y, agent_x = self.state[0] * 2 + 1, self.state[1] * 2 + 1

        maze_render[start_y, start_x] = 'S'
        maze_render[goal_y, goal_x] = 'G'
        maze_render[agent_y, agent_x] = 'A'

        # Print the maze
        for row in maze_render:
            print(''.join(row))
        print("\n")

        # Print binary representation
        print("Binary representation of the maze state:")
        self.render_binary()

In [7]:
import gymnasium as gym
from gymnasium import spaces
import numpy as np

class CustomMazeEnvMlpML(gym.Env):
    def __init__(self, max_steps_per_episode=100, maze_data_list=None, maze_size=10, random_start=False):
        super(CustomMazeEnvMlpML, self).__init__()
        
        
        # Define the size of the maze
        self.maze_size = maze_size
        self.max_steps_per_episode = max_steps_per_episode
        
        # Define action and observation space
        self.action_space = spaces.Discrete(4)  # [0: up, 1: right, 2: down, 3: left]
        self.observation_space = spaces.Box(low=0, high=1, shape=(self.maze_size * self.maze_size,), dtype=np.uint8)

        self.mazes = []
        self.current_maze_index = 0
        self.random_start = random_start
        self.episode = 0
        
        self.reward = 0
        self.done = False
        self.is_success = False

        # Initial state
        self.state = None
        self.start = None
        self.goal = (self.maze_size - 1, self.maze_size - 1)

        # Initialize visit counts
        self.visit_counts = np.zeros((self.maze_size, self.maze_size), dtype=np.int32)
        self.current_step = 0

        for maze_data in maze_data_list:
            self.mazes.append(self.initialize_maze(maze_data))
        
        self.maze = self.mazes[self.current_maze_index]
        

    def initialize_maze(self, input_string):
        maze_size = self.maze_size
        rows = input_string.strip().split('\n')

        top_wall = np.zeros((maze_size, maze_size), dtype=np.uint8)
        right_wall = np.zeros((maze_size, maze_size), dtype=np.uint8)
        bottom_wall = np.zeros((maze_size, maze_size), dtype=np.uint8)
        left_wall = np.zeros((maze_size, maze_size), dtype=np.uint8)

        parsed_data = []
        for row in rows:
            parsed_data.append([int(x) for x in row.split(';') if x != ''])


        for i in range(maze_size):
            for j in range(maze_size):
                state_index = i * maze_size + j
                actions = parsed_data[state_index]
                bottom_wall[i, j] = 1 if actions[0] == -10 else 0
                right_wall[i, j] = 1 if actions[1] == -10 else 0
                left_wall[i, j] = 1 if actions[2] == -10 else 0
                top_wall[i, j] = 1 if actions[3] == -10 else 0

        return np.stack([top_wall, right_wall, bottom_wall, left_wall], axis=0)

    def _get_obs(self):
        obs = np.zeros(self.maze_size * self.maze_size, dtype=np.uint8)
        obs[self.state[0] * self.maze_size + self.state[1]] = 1  # Agent position
        return obs

    def reset(self, seed=42, options=None):
        # Reset the state of the environment to an initial state
        new_seed = seed + self.episode
        super().reset(seed=new_seed)
        self.episode += 1

        if not self.random_start:
            self.start = (0, 0)
        else:
            self.start = (self.np_random.integers(0, self.maze_size), self.np_random.integers(0, self.maze_size))
        
        self.current_step = 0
        self.state = self.start
        self.visit_counts[self.state] += 1

        self.current_maze_index = (self.current_maze_index + 1) % len(self.mazes)
        self.maze = self.mazes[self.current_maze_index]
        return self._get_obs(), {}

    def step(self, action):
        self.current_step += 1
        
        x, y = self.state
        new_x, new_y = x, y

        # Define possible moves
        if action == 0:  # up
            new_x = max(0, x - 1)
        elif action == 1:  # right
            new_y = min(self.maze_size - 1, y + 1)
        elif action == 2:  # down
            new_x = min(self.maze_size - 1, x + 1)
        elif action == 3:  # left
            new_y = max(0, y - 1)

        # Check for walls or boundaries
        wall_hit = False
        if action == 0 and (x == 0 or self.maze[0, x, y] == 1):  # Top wall or top edge
            wall_hit = True
        elif action == 1 and (y == self.maze_size - 1 or self.maze[1, x, y] == 1):  # Right wall or right edge
            wall_hit = True
        elif action == 2 and (x == self.maze_size - 1 or self.maze[2, x, y] == 1):  # Bottom wall or bottom edge
            wall_hit = True
        elif action == 3 and (y == 0 or self.maze[3, x, y] == 1):  # Left wall or left edge
            wall_hit = True
        
        # Determine reward and update state
        if wall_hit:
            self.reward = -10
        else:
            self.state = (new_x, new_y)
            if self.state == self.goal:
                self.reward = 10
            else:
                self.reward = -1  # Default step cost
        
        self.visit_counts[self.state] += 1

        # Check if goal is reached or max steps are reached
        self.done = False
        self.is_success = False
        if self.state == self.goal:
            self.done = True
            self.is_success = True
        elif self.current_step >= self.max_steps_per_episode:
            self.done = True
            self.is_success = False
        
        return self._get_obs(), self.reward, self.done, False, {"is_success": self.is_success}
    
    def render(self, mode='human'):
        maze_render = np.full((self.maze_size * 2 + 1, self.maze_size * 2 + 1), ' ', dtype=str)
        
        # Draw walls
        for i in range(self.maze_size):
            for j in range(self.maze_size):
                cell_y, cell_x = i * 2 + 1, j * 2 + 1
                if self.maze[0, i, j]:  # Top wall
                    maze_render[cell_y - 1, cell_x] = '─'
                if self.maze[1, i, j]:  # Right wall
                    maze_render[cell_y, cell_x + 1] = '│'
                if self.maze[2, i, j]:  # Bottom wall
                    maze_render[cell_y + 1, cell_x] = '─'
                if self.maze[3, i, j]:  # Left wall
                    maze_render[cell_y, cell_x - 1] = '│'

        # Mark start, goal, and current position
        start_y, start_x = 1, 1
        goal_y, goal_x = self.maze_size * 2 - 1, self.maze_size * 2 - 1
        agent_y, agent_x = self.state[0] * 2 + 1, self.state[1] * 2 + 1

        maze_render[start_y, start_x] = 'S'
        maze_render[goal_y, goal_x] = 'G'
        maze_render[agent_y, agent_x] = 'A'

        # Print the maze
        for row in maze_render:
            print(''.join(row))
        print("\n")

In [8]:
import torch as th
import torch.nn as nn
from stable_baselines3.common.torch_layers import BaseFeaturesExtractor
import gymnasium as gym

class CustomCNN(BaseFeaturesExtractor):
    def __init__(self, observation_space: gym.spaces.Box, features_dim: int = 100):
        super(CustomCNN, self).__init__(observation_space, features_dim)
        
        # The input will now have the channel dimension first
        n_input_channels = observation_space.shape[0]
        
        self.cnn = nn.Sequential(
            nn.Conv2d(n_input_channels, 32, kernel_size=(3, 3), stride=(1, 1)),
            nn.ReLU(),
            nn.Conv2d(32, 64, kernel_size=(3, 3), stride=(1, 1)),
            nn.ReLU(),
            nn.Flatten()
        )

        # Compute shape by doing one forward pass
        with th.no_grad():
            n_flatten = self.cnn(
                th.as_tensor(observation_space.sample()[None]).float()
            ).shape[1]
        
        self.linear = nn.Linear(n_flatten, features_dim)
        
    def forward(self, observations: th.Tensor) -> th.Tensor:
        return self.linear(self.cnn(observations))

# Create the DQN model with CustomCNN
policy_kwargs = dict(
    features_extractor_class=CustomCNN,
    net_arch=[64,64]
)

2024-08-07 02:32:04.348949: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-08-07 02:32:04.349056: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-08-07 02:32:04.482134: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered


In [9]:
# Create the environment
# env = CustomMazeEnvMlp(maze_data=MAZE_DATA)
# env = CustomMazeEnvCNNIMG(maze_data=MAZE_DATA)
# env = CustomMazeEnv(maze_data=MAZE_DATA)
# env = CustomMazeEnvMlpImproved(maze_data=MAZE_DATA)
env = CustomMazeEnvCNNIMGML(maze_data_list=maze_data_list, max_steps_per_episode=1, maze_size=10, random_start=True)

# Verify the environment
print("Observation space:", env.observation_space)
print("Action space:", env.action_space)

# Test the environment with random actions
obs, _ = env.reset(42)
for _ in range(10):
    # action = env.action_space.sample()  # take a random action
    action = 1
    obs, reward, terminated, truncated, info = env.step(action)
    print("State:", env.state, "Action:", action, "Reward:", reward, "Terminated:", terminated, "Truncated:", truncated)
    env.render()
    # env.render_binary()
    print(obs)
    if terminated or truncated:
        obs, _ = env.reset()

Observation space: Box(0, 255, (84, 84, 3), uint8)
Action space: Discrete(4)
State: (0, 8) Action: 1 Reward: -1 Terminated: True Truncated: True
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [  0   0   0]
  ...
  [255 255 255]
  [  0   0   0]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]
State: (5, 6) Action: 1 Reward: -10 Terminated: True Truncated: True
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ..

In [10]:
import wandb
wandb.login(key="3e0201b52f7e9c9458608859c4e12c2d7b64a9b8")

Error: no "view" mailcap rules found for type "image/png"
Error: no "view" mailcap rules found for type "image/png"
Error: no "view" mailcap rules found for type "image/png"
Error: no "view" mailcap rules found for type "image/png"
Error: no "view" mailcap rules found for type "image/png"
Error: no "view" mailcap rules found for type "image/png"
/usr/bin/xdg-open: 869: www-browser: not found
/usr/bin/xdg-open: 869: www-browser: not found
/usr/bin/xdg-open: 869: www-browser: not found
/usr/bin/xdg-open: 869: www-browser: not found
/usr/bin/xdg-open: 869: links2: not found
/usr/bin/xdg-open: 869: www-browser: not found
/usr/bin/xdg-open: 869: www-browser: not found
/usr/bin/xdg-open: 869: links2: not found
/usr/bin/xdg-open: 869: links2: not found
/usr/bin/xdg-open: 869: links2: not found
/usr/bin/xdg-open: 869: links2: not found
/usr/bin/xdg-open: 869: elinks: not found
/usr/bin/xdg-open: 869: links2: not found
/usr/bin/xdg-open: 869: elinks: not found
/usr/bin/xdg-open: 869: elinks: no

True

In [11]:
import wandb
import torch
from stable_baselines3.common.callbacks import BaseCallback

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

class WandbCallbackMod(BaseCallback):
    def __init__(self, verbose=0):
        super().__init__(verbose)
        self.cumulative_reward = 0
        self.episode_reward = 0
        self.success_count = 0
        self.episode_count = 0

    def _on_step(self):
        # Log all available metrics from the logger
        for key, value in self.model.logger.name_to_value.items():
            wandb.log({key: value}, step=self.num_timesteps)
        
        reward = self.model.env.get_attr('reward')[0]
        
        self.cumulative_reward += reward
        self.episode_reward += reward
        
        if self.model.env.get_attr('done')[0]:
            # Increment the episode count
            self.episode_count += 1
            
            # If the episode was successful, increment the success count
            if self.model.env.get_attr('is_success')[0]:
                self.success_count += 1
            
            wandb.log({
                'train/cumulative_reward': self.cumulative_reward,
                'train/episode_reward': self.episode_reward,
                'train/success_rate': self.success_count / self.episode_count
            }, step=self.num_timesteps)
            
            # Reset the episode reward
            self.episode_reward = 0

        return True
    
    def _on_training_end(self):
        wandb.finish()
        
        return None

In [12]:
from stable_baselines3 import DQN

env_mlp_ml = CustomMazeEnvMlpML(maze_data_list=maze_data_list_alot, max_steps_per_episode=400, maze_size=10, random_start=True)

model_mlp_ml = DQN(
    "MlpPolicy",
    env_mlp_ml,
    learning_rate=1e-4,
    buffer_size=1000,
    learning_starts=100,
    batch_size=32,
    gamma=0.85,
    target_update_interval=5,
    exploration_fraction = 0.8,
    exploration_initial_eps=1.0,
    exploration_final_eps=0.5,
    device=device,
    verbose=1,
    seed=42,
)

callback = WandbCallbackMod()

Using cuda device
Wrapping the env with a `Monitor` wrapper
Wrapping the env in a DummyVecEnv.


In [14]:
wandb.init(project="maze-dqn", name="stable-mlp-maze-10-5-testcount")

wandb: Currently logged in as: jeremyrio (jeremyrp). Use `wandb login --relogin` to force relogin


In [ ]:
model_mlp_ml.learn(total_timesteps=2000000, callback=[callback], log_interval=1000)

/opt/conda/lib/python3.10/site-packages/gymnasium/core.py:297: UserWarning: WARN: env.reward to get variables from other wrappers is deprecated and will be removed in v1.0, to get this variable you can do `env.unwrapped.reward` for environment variables or `env.get_attr('reward')` that will search the reminding wrappers.
  logger.warn(
/opt/conda/lib/python3.10/site-packages/gymnasium/core.py:297: UserWarning: WARN: env.done to get variables from other wrappers is deprecated and will be removed in v1.0, to get this variable you can do `env.unwrapped.done` for environment variables or `env.get_attr('done')` that will search the reminding wrappers.
  logger.warn(
/opt/conda/lib/python3.10/site-packages/gymnasium/core.py:297: UserWarning: WARN: env.is_success to get variables from other wrappers is deprecated and will be removed in v1.0, to get this variable you can do `env.unwrapped.is_success` for environment variables or `env.get_attr('is_success')` that will search the reminding wrapp

In [ ]:
model_mlp_ml.save("stable-mlp-maze-10-5-testcount")